### ISSUE TITLE
Please Add the license to the project

### ISSUE THREAD

**Issue by gbatalski** [luciopanepinto/pacman#2]
Could you please add the License to the project, so one could decide about the usage possibilities. Regards, Gena

**Comment by luciopanepinto** [comment]
Ok, i will add the licence.
Thanks.

2017-07-07 23:48 GMT+02:00 Gena Batalski <notifications@github.com>:

**Comment by Dpuzak** [comment]
Yeah it would be lovely to see a license. I'm doing a simple marketing game and looking for an open source or cheap purchasable game I can customize without writing it from scratch. I found about your game because it's being sold through codecanyon illegaly from what I see in the comments. Let me know if it is ok to use it or is there a place where a license can be purchased if not.

https://codecanyon.net/item/pacman-html5-game/20759906

UPDATE: Btw I'll write a small server side top list feature if I use your game bacuse thats what I need and I'm glad to do a pull request once it's done if you think that will be usefull. It will probably be in node.js if it happens.
